// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace podcast_player_BE.Migrations
{
    [DbContext(typeof(PodcastPlayerDbContext))]
    partial class PodcastPlayerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("podcast_player_BE.Models.Playlist", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PodcastID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PodcastQuantity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Image = "playlist1.jpg",
                            OwnerID = "1",
                            PodcastID = "1,2,3",
                            PodcastQuantity = "3",
                            Title = "Playlist 1"
                        },
                        new
                        {
                            Id = "2",
                            Image = "playlist2.jpg",
                            OwnerID = "2",
                            PodcastID = "2,3",
                            PodcastQuantity = "2",
                            Title = "Playlist 2"
                        },
                        new
                        {
                            Id = "3",
                            Image = "playlist3.jpg",
                            OwnerID = "3",
                            PodcastID = "3",
                            PodcastQuantity = "1",
                            Title = "Playlist 3"
                        });
                });

            modelBuilder.Entity("podcast_player_BE.Models.PlaylistPodcast", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("PlaylistId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PodcastId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlaylistPodcasts");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            PlaylistId = "1",
                            PodcastId = "1"
                        },
                        new
                        {
                            Id = "2",
                            PlaylistId = "1",
                            PodcastId = "2"
                        },
                        new
                        {
                            Id = "3",
                            PlaylistId = "1",
                            PodcastId = "3"
                        },
                        new
                        {
                            Id = "4",
                            PlaylistId = "2",
                            PodcastId = "2"
                        },
                        new
                        {
                            Id = "5",
                            PlaylistId = "2",
                            PodcastId = "3"
                        },
                        new
                        {
                            Id = "6",
                            PlaylistId = "3",
                            PodcastId = "3"
                        });
                });

            modelBuilder.Entity("podcast_player_BE.Models.Podcast", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Podcasts");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Author = "Author 1",
                            Description = "Description 1",
                            Image = "image1.jpg",
                            Length = 30,
                            Name = "Podcast 1"
                        },
                        new
                        {
                            Id = "2",
                            Author = "Author 2",
                            Description = "Description 2",
                            Image = "image2.jpg",
                            Length = 45,
                            Name = "Podcast 2"
                        },
                        new
                        {
                            Id = "3",
                            Author = "Author 3",
                            Description = "Description 3",
                            Image = "image3.jpg",
                            Length = 60,
                            Name = "Podcast 3"
                        });
                });

            modelBuilder.Entity("podcast_player_BE.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            FullName = "John Doe",
                            Uid = "user1"
                        },
                        new
                        {
                            Id = "2",
                            FullName = "Jane Smith",
                            Uid = "user2"
                        },
                        new
                        {
                            Id = "3",
                            FullName = "Alice Johnson",
                            Uid = "user3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
